/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four
million, find the sum of the even-valued terms.
*/

// Generate fib numbers
// Find all even numbers
// Sum all even numbers

var fibEven = function() {
  fibNumbers = [1,2];

  while (fibNumbers[fibNumbers.length - 1] < 4000000) {
    fibNumbers.push(fibNumbers[fibNumbers.length - 1] + fibNumbers[fibNumbers.length - 2]);
  }

  // last element is greater than 4million, so remove it
  fibNumbers.pop();
  
  return fibNumbers.reduce(function(sum, fibNumber) {
    return fibNumber % 2 === 0 ? sum += fibNumber : sum += 0;
  }, 0);

}

console.log(fibEven());